MbmStore/Controllers/CatalogueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MbmStore.Models;
using MbmStore.Infrastructure;
using MbmStore.ViewModels;

namespace MbmStore.Controllers
{
    public class CatalogueController : Controller
    {
        public int PageSize = 4;

        // GET: Catalogue
        public ActionResult Index(string category, int page = 1)
        {

            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = Repository.Products
                .Where(p => category == null || p.Category == category)
                .OrderBy(p => p.ProductId)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),

                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ?
                    Repository.Products.Count() :
                    Repository.Products.Where(e => e.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
         
        }
    }
}

MbmStore/Controllers/CustomerController.cs
using MbmStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MbmStore.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Customer
        public ActionResult Index()
        {
            IList<Customer> Customers = new List<Customer>();

            Customers = Repository.customers.OfType<Customer>().ToList();

            ViewBag.customers = Repository.customers;
            return View();
        }
    }
}

MbmStore/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MbmStore.Models;

namespace MbmStore.Controllers
{
    public class InvoiceController : Controller
    {
        //Declare the list
        private List<SelectListItem> customers = new List<SelectListItem>();

        // GET: Invoice
        public ActionResult Index()
        {
            

            //Generate the dropdown list
            foreach (Invoice invoice in Repository.Invoices)
            {
                customers.Add(new SelectListItem { Text = invoice.Customer.Firstname + " " + 
                    invoice.Customer.Lastname, Value = invoice.Customer.CustomerId.ToString() });

            }

            //Removes duplicate entries with same ID from a IEnumerable
            customers = customers.GroupBy(x => x.Value).Select(y => y.First()).OrderBy(z => z.Text).ToList<SelectListItem>();
            ViewBag.CustomerId = customers;

            //Old
            IList<Invoice> invoices = new List<Invoice>();

            invoices = Repository.Invoices.OfType<Invoice>().ToList();

            ViewBag.Invoices = Repository.Invoices;
            return View();
        }

        [HttpPost]
        public ActionResult Index(int? CustomerId)
        {
            //Old
            IEnumerable<Invoice> invoices = new List<Invoice>();

            invoices = Repository.Invoices.OfType<Invoice>().ToList();


            //Generate the dropdown list
            foreach (Invoice invoice in Repository.Invoices)
            {
                customers.Add(new SelectListItem
                {
                    Text = invoice.Customer.Firstname + " " +
                    invoice.Customer.Lastname,
                    Value = invoice.Customer.CustomerId.ToString()
                });

            }

            customers = customers.GroupBy(x => x.Value).Select(y => y.First()).OrderBy(z => z.Text).ToList<SelectListItem>();

            
            if (CustomerId != null)
            {
                //Select invoices for a customer with linq
                invoices = Repository.Invoices.Where(r => r.Customer.CustomerId == CustomerId);
            }
            ViewBag.CustomerId = customers;
            ViewBag.Invoices = invoices;
            return View();
        }
    }
}

MbmStore/Controllers/NavController.cs
using MbmStore.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MbmStore.Controllers
{
    public class NavController : Controller
    {
        // GET: Nav
        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = Repository.Products
            .Select(x => x.Category)
            .Distinct()
            .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

MbmStore/Views/Shared/ProductSummaryBook.cshtml
@model MbmStore.Models.Book

<div class="row">
    <div class="col-md-3">
        <img src="/Content/Images/@Model.ImageUrl" alt="@Model.Title" style="width:100px" />
    </div>
    <div class="col-md-7">
        <strong>Title:</strong> @Model.Title<br />
        <strong>Author:</strong> @Model.Author<br />
        <strong>Price:</strong> @Model.Price<br />
        <strong>Publisher:</strong> @Model.Publisher (@Model.Published)<br />
        <strong>ISBN:</strong> @Model.ISBN<br /> <br />
    </div>
    <div class="col-md-2">
        @using (Html.BeginForm("AddToCart", "Cart"))
        {
            @Html.Hidden("ProductId", Model.ProductId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to cart" />
        }
    </div>
</div>

MbmStore/Views/Shared/ProductSummaryMovie.cshtml
@model MbmStore.Models.Movie

<div class="row">
    <div class="col-md-3">
        <img src="~/Content/Images/@Model.ImageUrl" alt="@Model.Title" />
    </div>

    <div class="col-md-7">
        <p><span>Title: </span>@Model.Title @Model.ProductId</p>
        <p><span>Director: </span>@Model.Director</p>
        <p><span>Price: </span>@String.Format("{0:00.00}", Model.Price)</p>
    </div>
    <div class="col-md-2">
        @using (Html.BeginForm("AddToCart", "Cart"))
            {
            @Html.Hidden("ProductId", Model.ProductId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to cart" />
        }
    </div>

</div>

MbmStore/Views/Shared/ProductSummaryMusic.cshtml
@using MbmStore.Models;
@model MbmStore.Models.MusicCD

<div class="row">
    <div class="col-md-3">
        <img src="~/Content/Images/@Model.ImageUrl" alt="@Model.Title" />
    </div>
    <div class="col-md-7">
        <div>
            <p><span>Album: </span>@Model.Title @Model.ProductId</p>
            <p><span>Artist: </span>@Model.Artist</p>
            <p><span>Price: </span>@String.Format("{0:00.00}", Model.Price)</p> @*@String.Format("{0:0:00}",music.Price)*@
            <p><span>Label: </span>@Model.Label (@Model.Released)</p>
        </div>
        <div class="tracks">
            <p><span>Tracks:</span></p>
            <ol>
                @foreach (Track track in Model.Tracks)
            {
                    <li>@track.Title (@track.Composer) @track.Length</li>
                }
            </ol>
            <p><span>Total playing time: </span>@Model.GetPlayingTime()</p>
        </div>
    </div>
    
    <div class="col-md-2">
        @using (Html.BeginForm("AddToCart", "Cart"))
        {
            @Html.Hidden("ProductId", Model.ProductId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to cart" />
        }
    </div>
    
</div>

MbmStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
    <style>
        img {
            max-width:90%;
        }
    </style>
</head>
<body class="">
 
        <nav class="navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                    @Html.ActionLink("MbmStore", "Index", "Catalogue", null, new { @class = "navbar-brand" })
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Customers", "Index", "Customer")</li>
                        <li>@Html.ActionLink("Invoices", "Index", "Invoice")</li>
                        @Html.Action("Summary", "Cart")
                    </ul>
                </div>
            </div>
        </nav>
        
    
    <div class="container">
        <div class="row">
            <div id="categories" class="col-xs-2">
                @Html.Action("Menu", "Nav")
            </div>
            <div class="col-xs-10">
                @RenderBody()
            </div>
        </div>
    </div>
    
</body>
</html>